### ISSUE TITLE
ClassNotFoundException when using clipboard plugin in android

### ISSUE THREAD

**Issue by rabee1981** [ionic-team/ionic-native#1736]
[x] bug report
[ ] feature request

I am try to use [clipboard plugin](https://ionicframework.com/docs/native/clipboard/) in my project, it works fine in ios but in android i got
```
java.lang.ClassNotFoundException: com.verso.cordova.clipboard.Clipboard
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:324)
    at java.lang.Class.forName(Class.java:285)
    at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
    at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
    at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
    at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

my package.json

```
"dependencies": {
        "@angular/common": "4.1.2",
        "@angular/compiler": "4.1.2",
        "@angular/compiler-cli": "4.1.2",
        "@angular/core": "4.1.2",
        "@angular/forms": "4.1.2",
        "@angular/http": "4.1.2",
        "@angular/platform-browser": "4.1.2",
        "@angular/platform-browser-dynamic": "4.1.2",
        "@ionic-native/camera": "^3.12.1",
        "@ionic-native/clipboard": "^3.12.1",
        "@ionic-native/core": "3.10.2",
        "@ionic-native/facebook": "^3.12.1",
        "@ionic-native/network": "^3.12.1",
        "@ionic-native/social-sharing": "^3.12.1",
        "@ionic-native/splash-screen": "3.10.2",
        "@ionic-native/status-bar": "3.10.2",
        "@ionic/storage": "2.0.1",
        "angularfire2": "^4.0.0-rc.0",
        "chart.js": "^2.6.0",
        "com.danielsogl.cordova.clipboard": "~1.0.2",
        "com.phonegap.plugins.facebookconnect": "file:src/phonegap-facebook-plugin",
        "cordova-android": "^6.2.3",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "1.0.5",
        "cordova-plugin-device": "1.1.4",
        "cordova-plugin-network-information": "^1.3.3",
        "cordova-plugin-splashscreen": "~4.0.1",
        "cordova-plugin-statusbar": "2.2.2",
        "cordova-plugin-whitelist": "1.3.1",
        "cordova-plugin-x-socialsharing": "^5.1.8",
        "danielsogl-cordova-plugin-clipboard": "^1.0.2",
        "es6-promise-plugin": "^4.1.0",
        "firebase": "^4.0.0",
        "ionic-angular": "3.3.0",
        "ionic-plugin-keyboard": "~2.2.1",
        "ionicons": "3.0.0",
        "ng2-charts": "^1.5.0",
        "rxjs": "5.1.1",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.11"
    },
    "devDependencies": {
        "@ionic/app-scripts": "1.3.7",
        "@ionic/cli-plugin-cordova": "1.4.0",
        "@ionic/cli-plugin-ionic-angular": "1.3.1",
        "typescript": "2.3.3"
    },
    "cordovaPlugins": [
        "cordova-plugin-whitelist",
        "cordova-plugin-console",
        "cordova-plugin-statusbar",
        "cordova-plugin-device",
        "cordova-plugin-splashscreen",
        "ionic-plugin-keyboard"
    ],
    "cordovaPlatforms": [
        "ios",
        {
            "platform": "ios",
            "version": "",
            "locator": "ios"
        }
    ],
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-x-socialsharing": {},
            "cordova-plugin-network-information": {},
            "cordova-plugin-camera": {
                "CAMERA_USAGE_DESCRIPTION": " ",
                "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
            },
            "com.danielsogl.cordova.clipboard": {}
        },
        "platforms": [
            "android",
            "ios"
        ]
    }
}
 
```
I am already try to remove and add platform but still not working

thanks in advance

**Comment by ihadeed** [comment]
Uninstall `com.danielsogl.cordova.clipboard` and install `cordova-clipboard`.
