### ISSUE TITLE
Unable to Install Ionic Native Screen Orientation

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-native#1778]
_From @iamchairs on July 6, 2017 21:31_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

```
PS C:\dev\theatreApp> ionic cordova plugin add cordova-plugin-screen-orientation
> cordova plugin add cordova-plugin-screen-orientation --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add cordova-plugin-screen-orientation --save (exit code 1):

        Installing "cordova-plugin-screen-orientation" for android
        Failed to install 'cordova-plugin-screen-orientation': Error
        at C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:205:33
        at _rejected
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:864:24)
        at C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:890:30
        at Promise.when
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:1142:31)
        at Promise.promise.promiseDispatch
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:808:41)
        at C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:624:44
        at runSingle
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:137:13)
        at flush
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:95:7)
        at process._tickCallback (internal/process/next_tick.js:161:9)
        Error: Failed to fetch plugin https://github.com/vstirbu/PromisesPlugin.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! Error while executing:
        npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/vstirbu/PromisesPlugin.git
        npm ERR!
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR! exited with error code: 128

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Micah\AppData\Roaming\npm-cache\_logs\2017-07-06T21_26_15_824Z-debug.log
```

C:\Users\Micah\AppData\Roaming\npm-cache\_logs\2017-07-06T21_26_15_824Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Micah\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/vstirbu/PromisesPlugin.git',
1 verbose cli   '--save' ]
2 info using npm@5.1.0
3 info using node@v8.1.0
4 verbose npm-session 2417404b05243cca
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/vstirbu/PromisesPlugin.git Error while executing:
7 silly fetchPackageMetaData C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/vstirbu/PromisesPlugin.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData fatal: Unable to find remote helper for 'https'
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData exited with error code: 128
8 verbose stack Error: exited with error code: 128
8 verbose stack     at ChildProcess.onexit (C:\Users\Micah\AppData\Roaming\npm\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
8 verbose stack     at emitTwo (events.js:125:13)
8 verbose stack     at ChildProcess.emit (events.js:213:7)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
9 verbose cwd C:\dev\theatreApp\node_modules
10 verbose Windows_NT 10.0.15063
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Micah\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/vstirbu/PromisesPlugin.git" "--save"
12 verbose node v8.1.0
13 verbose npm  v5.1.0
14 error Error while executing:
14 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/vstirbu/PromisesPlugin.git
14 error
14 error fatal: Unable to find remote helper for 'https'
14 error
14 error exited with error code: 128
15 verbose exit [ 1, true ]
```

**Steps to reproduce:**

Follow installation instructions at https://ionicframework.com/docs/native/screen-orientation/

Run `ionic cordova plugin add cordova-plugin-screen-orientation`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v8.1.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0
```

_Copied from original issue: ionic-team/ionic#12279_

**Comment by jgw96** [comment]
_From @russcarver on July 7, 2017 4:50_

I've been dealing with this for a week as well.  Any update?

**Comment by jgw96** [comment]
_From @AmitMY on July 7, 2017 11:2_

Try removing your platforms & plugins folders, and `ionic cordova prepare`, and try again.

**Comment by russcarver** [comment]
I finally solved it by removing the plugin and running `cordova plugin add https://github.com/Exilz/cordova-plugin-screen-orientation.git --save`

**Comment by neoassyrian** [comment]
I'm having this issue locally and also in Ionic Legacy Build/Package in the cloud. 
I simply can't add a plugin that uses a URL.

**Comment by fdambrosio** [comment]
I have the same problem. 

```
Installing "cordova-plugin-screen-orientation" for android
Failed to install 'cordova-plugin-screen-orientation': CordovaError: Failed to fetch plugin https://github.com/vstirbu/PromisesPlugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
```

**Comment by tomcatmwi** [comment]
Guys, don't you want to fix this bug? It's a shame that a native component simply doesn't exist. Here is what I get when I try to install it.

Here is what actually happens on ionic cordova plugin add cordova-plugin-screen-orientation:

```
> cordova plugin add cordova-plugin-screen-orientation --save
C:\Program Files (x86)\OpenSSH\bin\sh.exe (10140): *** couldn't allocate cygwin heap, Win32 error 0, base 0x7F0000, top 0x7F5000, reserve_size 20480, allocsize 20480, page_const 4096
Error: Failed to fetch plugin git+https://github.com/Exilz/cordova-plugin-screen
-orientation.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf: Cloning into 'C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf'...
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf: C:\Program Files (x86)\OpenSSH\bin\sh.exe (10140): *** couldn't allocate cygwin heap, Win32 error 0, base 0x7F0000, top 0x7F5000, reserve_size 20480, allocsize 20480, page_const 4096
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf:       1 [main] sh 8964 sync_with_child: child 10140(0x1BC) died before initialization with status code 0x1
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf:     164 [main] sh 8964 sync_with_child: *** child state waiting for longjmp
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf: Cannot fork: Resource temporarily unavailable
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf:
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf: and the repository exists.
npm ERR! git clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git+https://github.com/Exilz/cordova-plugin-screen-orientation.git" "--production" "--save"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code 128    
npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\tomcat\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Exilz-cordova-plugin-screen-orientation-git-16e251fa C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf
npm ERR! Cloning into 'C:\Users\tomcat\AppData\Local\Temp\npm-9328-8a7aefe6\git-cache-cc84988e\bb17ab18427b91ea61289a7f6ab3a8bac822fecf'...
npm ERR! C:\Program Files (x86)\OpenSSH\bin\sh.exe (10140): *** couldn't allocate cygwin heap, Win32 error 0, base 0x7F0000, top 0x7F5000, reserve_size 20480, allocsize 20480, page_const 4096
npm ERR!     1 [main] sh 8964 sync_with_child: child 10140(0x1BC) died before initialization with status code 0x1
npm ERR!     164 [main] sh 8964 sync_with_child: *** child state waiting for longjmp
npm ERR! Cannot fork: Resource temporarily unavailable
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     f:\Cordova\timelapser\npm-debug.log
[ERROR] An error occurred while running cordova plugin add cordova-plugin-screen-orientation --save (exit code 1).

```

**Comment by ihadeed** [comment]
This isn't an ionic native issue.

I don't know why your npm is trying to fetch it from these Github forks..

You could try and install from
https://github.com/apache/cordova-plugin-screen-orientation instead of npm

Regards,
Ibby Hadeed

**Comment by fdambrosio** [comment]
it's not working

**Comment by Fision** [comment]
I have same error for a quite some time now. Also my coworkers on mac and linux get same error.
