### ISSUE TITLE
building native plugin fails

### ISSUE THREAD

**Issue by mateo666** [ionic-team/ionic-native#1955]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
when i build the native plugin project

**Steps to reproduce:**
npm run build

**Related code:**

```
{ Error: Command failed: /Users/mateo/Dev/Fortin/ionic/test/ionic-native/node_modules/.bin/ngc -p /Users/mateo/Dev/Fortin/ionic/test/ionic-native/.tmp/plugins/.DS_Store/tsconfig.json
Error File '/Users/mateo/Dev/Fortin/ionic/test/ionic-native/src/@ionic-native/plugins/.DS_Store/index.ts' not found.

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/mateo/Dev/Fortin/ionic/test/ionic-native/node_modules/.bin/ngc -p /Users/mateo/Dev/Fortin/ionic/test/ionic-native/.tmp/plugins/.DS_Store/tsconfig.json' }
Error building plugins.


Building .DS_Store failed.


Building .DS_Store failed.npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-native@4.2.1 build:modules: `node scripts/build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-native@4.2.1 build:modules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mateo/.npm/_logs/2017-09-07T21_27_33_318Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-native@4.2.1 build: `npm run clean && npm run lint && npm run build:core && npm run build:modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-native@4.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mateo/.npm/_logs/2017-09-07T21_27_33_339Z-debug.log
```

**Other information:**

**package.json info:**

```json
insert the content here
```

**Comment by mateo666** [comment]
found the problem 
deleting .DS_Store from the plugins dir

**Comment by zgluis** [comment]
@mateo666 's solution worked for me. .DS_Store file is probably hidden, just execute `rm .DS_Store` in the plugins dir.

**Comment by arun537** [comment]
removed .DS_Store file it worked for the first it worked fine. But now when I am trying to build it still throws the same error.
