### ISSUE TITLE
Android ExoPlayer doesn't work

### ISSUE THREAD

**Issue by darkokostic** [ionic-team/ionic-native#2256]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 FAILED
25 actionable tasks: 25 executed

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 18s
(node:11300) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:27: AAPT: error: resource style/ExoMediaButton.Rewind (aka io.ionic.starter:style/ExoMediaButton.Rewind) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:27: AAPT: error: resource id/exo_rew (aka io.ionic.starter:id/exo_rew) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:38: AAPT: error: resource style/ExoMediaButton.Play (aka io.ionic.starter:style/ExoMediaButton.Play) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:38: AAPT: error: resource id/exo_play (aka io.ionic.starter:id/exo_play) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:49: AAPT: error: resource style/ExoMediaButton.Pause (aka io.ionic.starter:style/ExoMediaButton.Pause) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:49: AAPT: error: resource id/exo_pause (aka io.ionic.starter:id/exo_pause) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:60: AAPT: error: resource style/ExoMediaButton.FastForward (aka io.ionic.starter:style/ExoMediaButton.FastForward) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:60: AAPT: error: resource id/exo_ffwd (aka io.ionic.starter:id/exo_ffwd) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:145: AAPT: error: resource id/exo_position (aka io.ionic.starter:id/exo_position) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:154: AAPT: error: resource id/exo_progress (aka io.ionic.starter:id/exo_progress) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:160: AAPT: error: resource id/exo_duration (aka io.ionic.starter:id/exo_duration) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:18: AAPT: error: resource id/exo_content_frame (aka io.ionic.starter:id/exo_content_frame) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:25: AAPT: error: resource id/exo_shutter (aka io.ionic.starter:id/exo_shutter) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:30: AAPT: error: resource id/exo_artwork (aka io.ionic.starter:id/exo_artwork) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:35: AAPT: error: resource id/exo_subtitles (aka io.ionic.starter:id/exo_subtitles) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:41: AAPT: error: resource id/exo_controller_placeholder (aka io.ionic.starter:id/exo_controller_placeholder) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:45: AAPT: error: resource id/exo_overlay (aka io.ionic.starter:id/exo_overlay) not found.
    
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:27: error: resource style/ExoMediaButton.Rewind (aka io.ionic.starter:style/ExoMediaButton.Rewind) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:27: error: resource id/exo_rew (aka io.ionic.starter:id/exo_rew) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:38: error: resource style/ExoMediaButton.Play (aka io.ionic.starter:style/ExoMediaButton.Play) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:38: error: resource id/exo_play (aka io.ionic.starter:id/exo_play) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:49: error: resource style/ExoMediaButton.Pause (aka io.ionic.starter:style/ExoMediaButton.Pause) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:49: error: resource id/exo_pause (aka io.ionic.starter:id/exo_pause) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:60: error: resource style/ExoMediaButton.FastForward (aka io.ionic.starter:style/ExoMediaButton.FastForward) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:60: error: resource id/exo_ffwd (aka io.ionic.starter:id/exo_ffwd) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:145: error: resource id/exo_position (aka io.ionic.starter:id/exo_position) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:154: error: resource id/exo_progress (aka io.ionic.starter:id/exo_progress) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_playback_control_view.xml:160: error: resource id/exo_duration (aka io.ionic.starter:id/exo_duration) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:18: error: resource id/exo_content_frame (aka io.ionic.starter:id/exo_content_frame) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:25: error: resource id/exo_shutter (aka io.ionic.starter:id/exo_shutter) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:30: error: resource id/exo_artwork (aka io.ionic.starter:id/exo_artwork) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:35: error: resource id/exo_subtitles (aka io.ionic.starter:id/exo_subtitles) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:41: error: resource id/exo_controller_placeholder (aka io.ionic.starter:id/exo_controller_placeholder) not found.
/media/darko/01D06E6CA97ED7D0/Empli/Inview Technology App/inview-technology-app/platforms/android/app/src/main/res/layout/exo_simple_player_view.xml:45: error: resource id/exo_overlay (aka io.ionic.starter:id/exo_overlay) not found.
error: failed linking file resources.

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:482)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:794)
        ... 48 more
Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:462)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValidatedPackage$1(QueueableAapt2.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:454)
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:411)
        at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
        at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : Linux 4.10

**Comment by ihadeed** [comment]
This is an issue with the plugin, please file an issue @ their repo.
