### ISSUE TITLE
"@ionic-native/onesignal" doesnt work anymore in any ionic project.

### ISSUE THREAD

**Issue by LaloCastilla** [ionic-team/ionic-native#2563]
Description:
we are working on a project of a hybrid app development using ionic framework. We have a few months working with onesignal since we integrated it to our app, Last Wednesday  @ionic-native/onesignal started to crash our app, we cant compile it since then, we have tried everything, different computers, brand new apps. but the error is the same. i have seen on the internet that some people started to have problems since that day too.

Environment

PACKAGE.JSON

  "name": "MyIonicProject",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/onesignal": "^4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/storage": "2.1.3",
    "cordova-android": "7.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.19",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "onesignal-cordova-plugin": "^2.4.1",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.10",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "onesignal-cordova-plugin": {}
    },
    "platforms": [
      "android"
    ]
  }
}

CONFIG.XML

Steps to Reproduce Issue:

1- Create any Ionic project example: "ionic start myApptest tabs"
2- Add the onesignal-cordova-plugin to your project
3- Install @ionic-native/onesignal package to your project
4- Attempt to run the app on a physical device using: "ionic cordova run android -l -c"
   
The application doesnt compile succesfully and the following error is shown in the terminal:

Anything else:
UP-TO-DATE
:CordovaLib:processDebugJavaRes
NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild
FAILED

FAILURE: Build failed with an exception.

What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
Could not find runtime.aar (android.arch.lifecycle:runtime:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.1.0/runtime-1.1.0.aar
Could not find livedata-core.aar (android.arch.lifecycle:livedata-core:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/lifecycle/livedata-core/1.1.0/livedata-core-1.1.0.aar
Could not find viewmodel.aar (android.arch.lifecycle:viewmodel:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/lifecycle/viewmodel/1.1.0/viewmodel-1.1.0.aar
Could not find runtime.aar (android.arch.core:runtime:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/core/runtime/1.1.0/runtime-1.1.0.aar

Try:
14 actionable tasks: 1 executed, 13 up-to-date
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Get more help at https://help.gradle.org

BUILD FAILED in 7s
(node:18744) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
Could not find runtime.aar (android.arch.lifecycle:runtime:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.1.0/runtime-1.1.0.aar
Could not find livedata-core.aar (android.arch.lifecycle:livedata-core:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/lifecycle/livedata-core/1.1.0/livedata-core-1.1.0.aar
Could not find viewmodel.aar (android.arch.lifecycle:viewmodel:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/lifecycle/viewmodel/1.1.0/viewmodel-1.1.0.aar
Could not find runtime.aar (android.arch.core:runtime:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/core/runtime/1.1.0/runtime-1.1.0.aar

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Get more help at https://help.gradle.org

BUILD FAILED in 7s
at ChildProcess.whenDone (C:\Users\Eduardo\Desktop\last\MyIonicProject\platforms\android\cordova\node_module
s\cordova-common\src\superspawn.js:169:23)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:18744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by thro
wing inside of an async function without a catch block, or by rejecting a promise which was not handled with .ca
tch(). (rejection id: 1)
(node:18744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise r
ejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any help will be appreciated.

**Comment by LaloCastilla** [comment]
I solved this issue by upgrading by upgrading andorid platform to 8.0 and by modifying the gradle.build like this:

```
buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
    }
}
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
    project.ext {
      defaultBuildToolsVersion="25.0.2" //String
      defaultMinSdkVersion=19 //Integer - Minimum requirement is Android 4.4
      defaultTargetSdkVersion=26 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=26 //Integer - We ALWAYS compile with the latest by default
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

i just added "google()" before jcenter() statement.

What i understand is that if your gradle version is 4.0 or higher you need to do it this way if its lower than 4.0 you should replace as @drubetti  did.  : )

If any of this doesnt solve your issue you can always look at this: https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/380#issuecomment-397795231
