### ISSUE TITLE
build  ionic4 plugin in ionic-native v5 branch get error.

### ISSUE THREAD

**Issue by huangminlinux** [ionic-team/ionic-native#2644]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

build  ionic4 plugin in ionic-native v5 branch get error.

**Steps to reproduce:**

```
clone ionic-native into ionic-native dir
cd ionic-native
git checkout v5
npm i
npm run build // get a error.
```

error log: 
```
Error: ENOENT: no such file or directory, open '/*********/ionic-native/dist/@ionic-native/plugins/.DS_Store/index.js'
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
> Ionic info
Ionic:

   ionic (Ionic CLI) : 4.1.0

System:

   NodeJS : v10.6.0
   npm    : 6.1.0
   OS     : macOS High Sierra
```

**Comment by rener172846** [comment]
I have the same issue. Have you found any solution?

**Comment by huangminlinux** [comment]
@rener172846  I have to re-download ionic-native-master and try again. It will be work

**Comment by rener172846** [comment]
@huangminlinux , Strange I just downloaded few hours ago, but got that issue. Which commit is related to fix that issue do you think?

**Comment by rener172846** [comment]
Tried with v5.2.0 again, but same issue
```
Error: ENOENT: no such file or directory, open '/Volumes/Work/Work/Ionic/Cuebiq/ionic-native/ionic-native/dist/@ionic-native/plugins/.DS_Store/index.js'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at /Volumes/Work/Work/Ionic/Cuebiq/ionic-native/ionic-native/scripts/tasks/build-esm.ts:21:27
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Volumes/Work/Work/Ionic/Cuebiq/ionic-native/ionic-native/scripts/tasks/build-esm.ts:16:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/Volumes/Work/Work/Ionic/Cuebiq/ionic-native/ionic-native/node_modules/ts-node/src/index.ts:413:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Volumes/Work/Work/Ionic/Cuebiq/ionic-native/ionic-native/node_modules/ts-node/src/index.ts:416:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-native@5.2.0 build:esm: `ts-node -P scripts/tsconfig.json scripts/tasks/build-esm`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-native@5.2.0 build:esm script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rener/.npm/_logs/2019-03-22T07_18_54_371Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-native@5.2.0 build: `npm run build:core && npm run build:esm && npm run build:ngx && npm run build:es5`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-native@5.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rener/.npm/_logs/2019-03-22T07_18_54_451Z-debug.log
```

**Comment by huangminlinux** [comment]
Are you try it in master branch ?

**Comment by rener172846** [comment]
yes, first time tried master branch, next tried v5.2.0

**Comment by huangminlinux** [comment]
I just try it in master branch, it work fine

**Comment by rener172846** [comment]
ok, thanks anyway. I will try again
