### ISSUE TITLE
geofence cause ionic 4.0.0.beta3 build error "... Error: Cannot find module '../cordova/platform_metadata' ..."

### ISSUE THREAD

**Issue by jing-zhou** [ionic-team/ionic-native#2667]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic 4.0.0.beta3 project build ('ionic cordova run android') failed with the follow error prompt:
`(node:9923) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cordova/platform_metadata'`
**Expected behavior:**

Ionic 4.0.0.beta3 project build ('ionic cordova run android') should succeed
**Steps to reproduce:**

1, following https://beta.ionicframework.com/docs to setup the environement
2, start a new project by 
`ionic start myApp tabs --type=angular`
follow prompt to finish the process, select 'y' to install cordova
3, enter the project folder , type in the following 
```
ionic cordova platform add android
ionic cordova plugin add cordova-plugin-geofence
npm install --save @ionic-native/geofence
```
4, type in 
`ionic cordova run android
`
and see the build fails and the error occurs
```
chunk {127} 127.js, 127.js.map () 3.92 kB  [rendered]
chunk {129} 129.js, 129.js.map () 10.5 kB  [rendered]
> cordova run android
Android Studio project detected
(node:9923) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cordova/platform_metadata'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Context.requireCordovaModule (/home/wjz/.nvm/versions/node/v10.7.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:77:12)
    at module.exports (/home/wjz/ion/uApp/plugins/cordova-plugin-add-swift-support/src/add-swift-support.js:23:34)
    at runScriptViaModuleLoader (/home/wjz/.nvm/versions/node/v10.7.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
    at runScript (/home/wjz/.nvm/versions/node/v10.7.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
    at /home/wjz/.nvm/versions/node/v10.7.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
    at _fulfilled (/home/wjz/.nvm/versions/node/v10.7.0/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
(node:9923) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9923) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
wjz@bj:~/ion/uApp$ ionic info
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/home/wjz/.nvm/versions/node/v10.7.0/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/wjz/Android/Sdk)
   NodeJS            : v10.7.0 (/home/wjz/.nvm/versions/node/v10.7.0/bin/node)
   npm               : 6.2.0
   OS                : Linux 4.4

Environment:

   HTTP_PROXY  : http://127.0.0.1:42266/
   http_proxy  : http://127.0.0.1:42266/
   HTTPS_PROXY : http://127.0.0.1:42266/
   https_proxy : http://127.0.0.1:42266/

wjz@bj:~/ion/uApp$ 
```

**Comment by jing-zhou** [comment]
this is a bug of the dependent plugin 'cordova-plugin-add-swift-support'. remove and reinstall 'cordova-plugin-add-swift-support' solves the problem 
see https://github.com/terikon/cordova-plugin-photo-library/issues/124
