### ISSUE TITLE
Fail to build 

### ISSUE THREAD

**Issue by aswanee** [ionic-team/ionic-native#2698]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
try to run command this command :**
- ionic cordova prepare ios --prod
or
- ionic cordova build ios --prod

**Expected behavior:**
Get Exception:**
Running app-scripts build: --prod --platform ios --target cordova
[14:35:48]  build prod started ...
[14:35:48]  clean started ...
[14:35:48]  clean finished in 16 ms
[14:35:48]  copy started ...
[14:35:49]  deeplinks started ...
[14:35:50]  deeplinks finished in 584 ms
[14:35:50]  ngc started ...
Error: Metadata version mismatch for module /Users/bnrashed/Desktop/a-finance/node_modules/@ionic-native/in-app-purchase-2/index.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/Users/bnrashed/Desktop/a-finance/node_modules/@angular/compiler/bundles/compiler.umd.js:25755:34)
    at StaticSymbolResolver._createSymbolsOf (/Users/bnrashed/Desktop/a-finance/node_modules/@angular/compiler/bundles/compiler.umd.js:25543:46)
    at StaticSymbolResolver.getSymbolsOf (/Users/bnrashed/Desktop/a-finance/node_modules/@angular/compiler/bundles/compiler.umd.js:25524:14)
    at /Users/bnrashed/Desktop/a-finance/node_modules/@angular/compiler/bundles/compiler.umd.js:24381:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (/Users/bnrashed/Desktop/a-finance/node_modules/@angular/compiler/bundles/compiler.umd.js:24380:79)
    at AotCompiler.analyzeModulesAsync (/Users/bnrashed/Desktop/a-finance/node_modules/@angular/compiler/bundles/compiler.umd.js:23936:47)
    at CodeGenerator.codegen (/Users/bnrashed/Desktop/a-finance/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/bnrashed/Desktop/a-finance/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at Object.doCodegen (/Users/bnrashed/Desktop/a-finance/node_modules/@ionic/app-scripts/dist/aot/codegen.js:6:51)
[14:35:54]  copy finished in 5.17 s

**Other information:**
this exception happen only if i tryed to use --prod with command 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:
    cordova (Cordova CLI) : 8.0.0

local packages:
    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.8.0

System:
    ios-deploy : 1.9.2
    Node       : v8.10.0
    npm        : 5.8.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4 Build version 9F1027a

Environment Variables:
    ANDROID_HOME : not set
Misc:
    backend : pro

**Comment by danielsogl** [comment]
You have to use Angular 5
