### ISSUE TITLE
Error on build with --prod and --release - Metadata version mismatch for module (found version 4, expected 3)

### ISSUE THREAD

**Issue by franzisk** [ionic-team/ionic-native#2728]
**I'm submitting a ...** 
[x] bug report

When I try to build to android using:
`% ionic cordova build android  --prod --release`

I get this error:
```
Error: Metadata version mismatch for module /Users/francisco/Projetos-Ionic/Jungery/node_modules/@ionic-native/core/decorators.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/compiler/bundles/compiler.umd.js:24474:34)
    at StaticSymbolResolver._createSymbolsOf (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/compiler/bundles/compiler.umd.js:24260:46)
    at StaticSymbolResolver.getSymbolsOf (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:14)
    at /Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/compiler/bundles/compiler.umd.js:23023:30
    at Array.forEach (native)
    at extractProgramSymbols (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/compiler/bundles/compiler.umd.js:23022:79)
    at AotCompiler.compileAll (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/compiler/bundles/compiler.umd.js:22720:47)
    at CodeGenerator.codegen (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/compiler-cli/src/codegen.js:30:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/compiler-cli/src/ngtools_api.js:61:30)
    at /Users/francisco/Projetos-Ionic/Jungery/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:182:73
```
I it also had happen with **angular-progress-bar** plugin, then I downgraded to a lower version and it worked.

Below is my package.json:
```
...
"dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/android-permissions": "4.14.0",
    "@ionic-native/background-geolocation": "4.14.0",
    "@ionic-native/barcode-scanner": "4.14.0",
    "@ionic-native/camera": "4.14.0",
    "@ionic-native/contacts": "4.14.0",
    "@ionic-native/core": "4.14.0",
    "@ionic-native/device": "4.14.0",
    "@ionic-native/email-composer": "4.14.0",
    "@ionic-native/facebook": "4.14.0",
    "@ionic-native/file": "4.14.0",
    "@ionic-native/geolocation": "4.14.0",
    "@ionic-native/globalization": "4.14.0",
    "@ionic-native/google-maps": "4.14.0",
    "@ionic-native/google-plus": "4.14.0",
    "@ionic-native/keyboard": "4.14.0",
    "@ionic-native/linkedin": "4.14.0",
    "@ionic-native/media": "4.14.0",
    "@ionic-native/native-audio": "4.14.0",
    "@ionic-native/native-geocoder": "4.14.0",
    "@ionic-native/native-page-transitions": "4.14.0",
    "@ionic-native/network": "4.14.0",
    "@ionic-native/push": "4.14.0",
    "@ionic-native/social-sharing": "4.14.0",
    "@ionic-native/splash-screen": "4.14.0",
    "@ionic-native/sqlite": "4.14.0",
    "@ionic-native/status-bar": "4.14.0",
    "@ionic-native/streaming-media": "4.14.0",
    "@ionic-native/twitter-connect": "4.14.0",
    "@ionic/storage": "^2.0.1",
    "@ngx-translate/core": "^7.1.0",
    "@ngx-translate/http-loader": "^0.1.0",
    "@techiediaries/ngx-qrcode": "0.0.5",
    "android-versions": "^1.3.0",
    "angular-progress-bar": "^1.0.1",
    "angular2-text-mask": "^8.0.4",
    "angularfire2": "^4.0.0-rc.0",
    "com.googlemaps.ios": "https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk",
    "com.telerik.plugins.nativepagetransitions": "~0.6.5",
    "cordova-android": "^6.3.0",
    "cordova-browser": "5.0.3",
    "cordova-ios": "^4.4.0",
    "cordova-plugin-add-swift-support": "^1.7.2",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-camera": "^2.4.1",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-crosswalk-webview": "^2.4.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-email-composer": "^0.8.15",
    "cordova-plugin-facebook4": "~1.9.1",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-geolocation": "^2.4.3",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git",
    "cordova-plugin-googleplus": "~5.2.3",
    "cordova-plugin-linkedin": "~1.2.1",
    "cordova-plugin-mauron85-background-geolocation": "~2.3.2",
    "cordova-plugin-media": "^5.0.2",
    "cordova-plugin-nativeaudio": "^3.0.9",
    "cordova-plugin-nativegeocoder": "^2.0.4",
    "cordova-plugin-network-information": "^1.3.4",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-streaming-media": "^2.1.3",
    "cordova-plugin-swift-support": "^3.1.1",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-plugin-x-socialsharing": "^5.2.1",
    "cordova-sqlite-storage": "^0.7.14",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "^3.9.0",
    "font-awesome": "^4.7.0",
    "ionic": "3.20.0",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic-tooltips": "^2.0.1",
    "ionicons": "3.0.0",
    "ngx-qrcode2": "0.0.5",
    "phonegap-plugin-barcodescanner": "^6.0.8",
    "phonegap-plugin-push": "^2.1.2",
    "promise-polyfill": "7.1.0",
    "run": "^1.4.0",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "twitter-connect-plugin": "https://github.com/chroa/twitter-connect-plugin",
    "web-animations-js": "^2.3.1",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.0",
    "typescript": "2.3.4"
  },
...

```

Ionic Info:
```
cli packages: (/Users/francisco/Projetos-Ionic/Jungery/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 6.3.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.12
    Node       : v7.0.0
    npm        : 5.3.0
    OS         : macOS High Sierra
    Xcode      : Xcode 10.0 Build version 10A255

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

Also, when I run "**npm list**" in the end I get this:
```
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/android-permissions@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/background-geolocation@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/barcode-scanner@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/camera@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/contacts@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/core@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/device@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/email-composer@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/facebook@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/file@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/geolocation@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/globalization@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/google-maps@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/google-plus@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/keyboard@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/linkedin@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/media@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/native-audio@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/native-geocoder@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/native-page-transitions@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/network@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/push@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/social-sharing@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/splash-screen@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/sqlite@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/status-bar@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/streaming-media@4.14.0
npm ERR! peer dep missing: rxjs@^5.5.11, required by @ionic-native/twitter-connect@4.14.0
npm ERR! missing: com.googlemaps.ios@git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git, required by jungery@1.0.1
npm ERR! missing: com.telerik.plugins.nativepagetransitions@~0.6.5, required by jungery@1.0.1
npm ERR! missing: cordova-plugin-facebook4@~1.9.1, required by jungery@1.0.1
npm ERR! missing: cordova-plugin-googleplus@~5.2.3, required by jungery@1.0.1
npm ERR! missing: cordova-plugin-linkedin@~1.2.1, required by jungery@1.0.1
npm ERR! missing: twitter-connect-plugin@git+https://github.com/chroa/twitter-connect-plugin.git, required by jungery@1.0.1
```

What would be this "**found version 4, expected 3**"?  Version 4 of what? Found where? And expected version 3 where?

Please, can anybody help?

**Comment by danielsogl** [comment]
You have to upgrade to Angular 5

**Comment by franzisk** [comment]
@danielsogl Where? How? Where did you see the Angular version?

**Comment by danielsogl** [comment]
In your package.jaon you posted I can see your Angular version 😬

**Comment by franzisk** [comment]
@danielcregg Thanks a lot for helping, I updated the Angular to 5 with:
`sudo npm install @angular/animations@5.0.0 @angular/common@5.0.0 @angular/compiler@5.0.0 @angular/compiler-cli@5.0.0 @angular/core@5.0.0 @angular/forms@5.0.0 @angular/http@5.0.0 @angular/platform-browser@5.0.0 @angular/platform-browser-dynamic@5.0.0 @angular/platform-server@5.0.0 @angular/router@5.0.0 typescript@2.4.2 rxjs@5.5.2`

And now I am getting this other error, it seems to be something on the storage, can you take a look please?
```
± % sudo ionic cordova build android  --prod --release                                                                                                                       Running app-scripts build: --prod --platform android --target cordova
[06:27:12]  build prod started ...
[06:27:12]  clean started ...
[06:27:12]  clean finished in 6 ms
[06:27:12]  copy started ...
[06:27:12]  deeplinks started ...
[06:27:13]  deeplinks finished in 972 ms
[06:27:13]  ngc started ...
[06:27:24]  typescript: node_modules/@ngx-translate/core/src/translate.service.d.ts, line: 1
            Module '"/Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/core/core"' has no exported member
            'OpaqueToken'.

       L1:  import { EventEmitter, OpaqueToken } from "@angular/core";
       L2:  import { Observable } from "rxjs/Observable";

[06:27:24]  typescript: node_modules/@ionic/storage/es2015/storage.d.ts, line: 2
            Module '"/Users/francisco/Projetos-Ionic/Jungery/node_modules/@angular/core/core"' has no exported member
            'OpaqueToken'.

       L1:  import { OpaqueToken } from '@angular/core';
       L3:   * Storage is an easy way to store key/value pairs and JSON objects.

Error: The Angular AoT build failed. See the issues above
    at /Users/francisco/Projetos-Ionic/Jungery/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:232:55
    at step (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/francisco/Projetos-Ionic/Jungery/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
[06:27:24]  copy finished in 11.91 s
```

**Comment by franzisk** [comment]
@danielcregg Thanks a lot for your help. I was able to build it after updating everything, still have some issues but those ones were solved.
