### ISSUE TITLE
@ionic-native/keyboard@4.15.0 giving  "Property 'hideKeyboardAccessoryBar' does not exist on type 'Keyboard'" error

### ISSUE THREAD

**Issue by shaharpan2912** [ionic-team/ionic-native#2764]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
 when trying to build with command "ionic cordova build browser" It gives following error for version 4.15.0
 but if I try with 4.14.0 it works fine.

*
**Stack Trace**
```
ionic-app-scripts build --prod "--target" "cordova" "--platform" "browser"

[13:03:47]  ionic-app-scripts 3.2.0 
[13:03:47]  build prod started ... 
[13:03:48]  clean started ... 
[13:03:48]  clean finished in 24 ms 
[13:03:48]  copy started ... 
[13:03:49]  deeplinks started ... 
[13:03:57]  deeplinks finished in 8.24 s 
[13:03:57]  ngc started ... 
[13:05:25]  typescript: src/app/app.component.ts, line: 393 
[13:05:25]  typescript: src/app/app.component.ts, line: 394 
[13:05:25]  typescript: src/pages/activity/activity.ts, line: 252 
[13:05:25]  typescript: src/pages/organization-details/organization-details.ts, line: 763 
[13:05:25]  ionic-app-script task: "build" 
[13:05:25]  Error: The Angular AoT build failed. See the issues above 
Error: The Angular AoT build failed. See the issues above
    at /app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:232:55
    at step (/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
            Property 'hideKeyboardAccessoryBar' does not exist on type 'Keyboard'. 

     L392:  this.showAppVersionAlert();
     L393:  this._keyboard.hideKeyboardAccessoryBar(false);
     L394:  this._keyboard.disableScroll(false);

            Property 'disableScroll' does not exist on type 'Keyboard'. 

     L393:  this._keyboard.hideKeyboardAccessoryBar(false);
     L394:  this._keyboard.disableScroll(false);
     L395:  this.statusBar.styleDefault();

            Property 'close' does not exist on type 'Keyboard'. 

     L251:  modal.onDidDismiss(data => {
     L252:    this._keyboard.close();
     L253:    this.orderVar = JSON.parse(data);

            Property 'close' does not exist on type 'Keyboard'. 

     L762:        modal.onDidDismiss(data => {
     L763:          this._keyboard.close();

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quarterly-mobile-app@0.0.1 ionic:build: `ionic-app-scripts build --prod "--target" "cordova" "--platform" "browser"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quarterly-mobile-app@0.0.1 ionic:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-05T13_05_25_833Z-debug.log
```
**Ionic info:** :

```


Ionic:

   ionic (Ionic CLI)  : 4.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 22 other plugins)

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.4
```

**Comment by danielsogl** [comment]
The function have been changed. Please check out the docs or this commit: https://github.com/ionic-team/ionic-native/pull/2743/files
