### ISSUE TITLE
Ionic [4.0.0-beta15] build failed with LocalNotifications[0.9.0-beta.2/3]

### ISSUE THREAD

**Issue by jing-zhou** [ionic-team/ionic-native#2807]
**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

the ionic 4.0.0-beta15  failed. see https://github.com/katzer/cordova-plugin-local-notifications/issues/1719
the 
**Expected behavior:**

**Steps to reproduce:**

1, integrate the "LocalNotifications", as  per the https://beta.ionicframework.com/docs/native/local-notifications

2, enter comamnd 

> ionic cordova run android 

3, the build failed after ~40 minutes with the following print-out 

```
... ...
:app:generateDebugSources UP-TO-DATE
:app:javaPreCompileDebug UP-TO-DATE
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:32: error: package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle;
                                                      ^
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:130: error: cannot find symbol
                .setChannelId(options.getChannel())
                ^
  symbol:   method setChannelId(String)
  location: class Builder
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:296: error: cannot find symbol
        MediaStyle style;
        ^
  symbol:   class MediaStyle
  location: class Builder
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:298: error: cannot find symbol
        style = new MediaStyle(builder)
                    ^
  symbol:   class MediaStyle
  location: class Builder
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:417: error: constructor Builder in class Builder cannot be applied to given types;
            builder = new NotificationCompat.Builder(context, options.getChannel());
                      ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 43m 44s
27 actionable tasks: 1 executed, 26 up-to-date
Command finished with error code 1: /home/wjz/ion/arhat/platforms/android/gradlew cdvBuildDebug,-b,/home/wjz/ion/arhat/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Dorg.gradle.jvmargs=-Xmx2048m,-Pandroid.useDeprecatedNdk=true
(node:22449) UnhandledPromiseRejectionWarning: Error: /home/wjz/ion/arhat/platforms/android/gradlew: Command failed with exit code 1 Error output:
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:32: error: package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle;
                                                      ^
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:130: error: cannot find symbol
                .setChannelId(options.getChannel())
                ^
  symbol:   method setChannelId(String)
  location: class Builder
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:296: error: cannot find symbol
        MediaStyle style;
        ^
  symbol:   class MediaStyle
  location: class Builder
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:298: error: cannot find symbol
        style = new MediaStyle(builder)
                    ^
  symbol:   class MediaStyle
  location: class Builder
/home/wjz/ion/arhat/platforms/android/app/src/main/java/de/appplant/cordova/plugin/notification/Builder.java:417: error: constructor Builder in class Builder cannot be applied to given types;
            builder = new NotificationCompat.Builder(context, options.getChannel());
                      ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 43m 44s
    at ChildProcess.whenDone (/home/wjz/ion/arhat/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
(node:22449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/home/wjz/.nvm/versions/node/v10.7.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-webview 2.0.2, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/wjz/Android/Sdk)
   NodeJS            : v10.7.0 (/home/wjz/.nvm/versions/node/v10.7.0/bin/node)
   npm               : 6.2.0
   OS                : Linux 4.15

Environment:

   HTTP_PROXY  : http://127.0.0.1:37245/
   http_proxy  : http://127.0.0.1:37245/
   HTTPS_PROXY : http://127.0.0.1:37245/
   https_proxy : http://127.0.0.1:37245/

```
"dependencies" section of package.json

```
"dependencies": {
    "@angular/common": "~6.1.1",
    "@angular/core": "~6.1.1",
    "@angular/forms": "~6.1.1",
    "@angular/http": "~6.1.1",
    "@angular/platform-browser": "~6.1.1",
    "@angular/platform-browser-dynamic": "~6.1.1",
    "@angular/router": "~6.1.1",
    "@ionic-native/background-mode": "5.0.0-beta.21",
    "@ionic-native/badge": "5.0.0-beta.21",
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/device": "5.0.0-beta.21",
    "@ionic-native/geofence": "5.0.0-beta.21",
    "@ionic-native/geolocation": "5.0.0-beta.21",
    "@ionic-native/globalization": "5.0.0-beta.21",
    "@ionic-native/local-notifications": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-beta.15",
    "@ionic/storage": "^2.1.3",
    "@ngx-translate/core": "11.0.0",
    "@ngx-translate/http-loader": "4.0.0",
    "base64-js": "^1.3.0",
    "client-oauth2": "^4.2.1",
    "cordova-android": "7.0.0",
    "cordova-plugin-add-swift-support": "^1.7.2",
    "cordova-plugin-background-mode": "^0.7.2",
    "cordova-plugin-badge": "^0.8.7",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-geofence": "^0.7.0",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-ionic-webview": "^2.0.2",
    "cordova-plugin-local-notification": "^0.9.0-beta.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.3.3",
    "core-js": "^2.5.3",
    "es6-promise-plugin": "^4.2.2",
    "fbsj": "^1.0.53",
    "flatbuffers": "1.10.2",
    "http-string-parser": "0.0.6",
    "moment": "^2.22.2",
    "rxjs": "6.2.2",
    "serialize-javascript": "^1.5.0",
    "text-encoding": "^0.6.4",
    "uuid": "^3.3.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.8.5",
    "@angular-devkit/build-angular": "~0.8.5",
    "@angular-devkit/core": "~0.8.5",
    "@angular-devkit/schematics": "~0.8.5",
    "@angular/cli": "~6.2.5",
    "@angular/compiler": "~6.1.1",
    "@angular/compiler-cli": "~6.1.1",
    "@angular/language-service": "~6.1.1",
    "@ionic/angular-toolkit": "^1.0.0",
    "@ionic/ng-toolkit": "^1.1.0",
    "@ionic/schematics-angular": "1.0.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "husky": "^1.1.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  },

```

**Comment by jing-zhou** [comment]
this turned out to be a build fault. the build process' failure in loading some dependencies had caused this problems
