### ISSUE TITLE
@ionic-native/in-app-purchase-2 fails to install after upgrade

### ISSUE THREAD

**Issue by nagthgr8** [ionic-team/ionic-native#2809]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
while installing the plugin from command line throws below exception this plugin was working before update

Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cc.fovea.cordova.purchase': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:221:7)
    at copyNewFile (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\lib\pluginHandlers.js:258:28)
    at install (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\lib\pluginHandlers.js:43:17)
    at ActionStack.process (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\Api.js:247:74
    at _fulfilled (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\MobileApps\HYBRID\vedichoroo\platforms\android\cordova\node_modules\q\q.js:863:30)
Uh oh!
The "path" argument must be of type string

**Expected behavior:**
The plugin should be installed
**Steps to reproduce:**

1. upgrade ionic & cordova to the latest(ref. to below ionic info)

2. remove & add android platform
>cordova platform rm android
>cordova platform add android

3. remove and add in-app-purchase-2 plugin
>ionic cordova plugin rm cc.fovea.cordova.purchase
>ionic cordova plugin add cc.fovea.cordova.purchase --variable BILLING_KEY="MYBILLINGKEY"

**Related code:**

```
insert any relevant code here
```

**Other information:**
I have googled on this issue & tried those methods which did not work

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
Ionic:

   ionic (Ionic CLI)  : 4.3.1 (C:\Users\Hamsini\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : no whitelisted plugins (13 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Hamsini\AppData\Local\Android\sdk)
   NodeJS            : v9.3.0 (C:\Program Files\nodejs\node.exe)
   npm               : 5.10.0
   OS                : Windows 10

```

**Comment by nagthgr8** [comment]
its a sad thing when something related to payment breaks after upgrades :(

**Comment by nagthgr8** [comment]
the issue resolved when i remove & then add platform android
>ionic cordova platform rm android
>ionic cordova platform add android
looks like this step is mandatory for every cordova update

**Comment by egorplatoshkin** [comment]
Hello  @nagthgr8, I have the same issue and your work around about this issue doesn't work for me.
`Failed to install 'cc.fovea.cordova.purchase': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)
    at copyNewFile (/home/yehor/Payment investigate/myApp1/platforms/android/cordova/lib/pluginHandlers.js:258:28)
    at install (/home/yehor/Payment investigate/myApp1/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/home/yehor/Payment investigate/myApp1/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/yehor/Payment investigate/myApp1/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/yehor/Payment investigate/myApp1/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /home/yehor/Payment investigate/myApp1/platforms/android/cordova/Api.js:247:74
    at _fulfilled (/home/yehor/Payment investigate/myApp1/platforms/android/cordova/node_modules/q/q.js:834:54)
    at /home/yehor/Payment investigate/myApp1/platforms/android/cordova/node_modules/q/q.js:863:30
Uh oh!
The "path" argument must be of type string. Received type undefined
`
My ionic info:

`Ionic:

   ionic (Ionic CLI)  : 4.3.1 (/usr/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/yehor/Android/Sdk)
   NodeJS            : v11.1.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15
`
I have same stack trace each time when run 

> ionic cordova platform add android
or
> ionic cordova emulate android

May be you have some advice which can help solve this issue?

**Comment by brodybits** [comment]
On Mon, Nov 19, 2018, 6:56 AM egorplatoshkin <notifications@github.com>
wrote:

> Hello @nagthgr8 <https://github.com/nagthgr8>, I have the same issue and
> your work around about this issue doesn't work for me.
> Failed to install 'cc.fovea.cordova.purchase': TypeError
>
[...]

> Cordovaa:
>
> cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
> Cordova Platforms : android 7.1.2
>

It is not possible to use the Cordova purchase plugin with Cordova Android
7.1.2 due to a known issue. We expect to release a cordova-android patch
fix this week. Until then please be sure to use cordova-android version
7.1.1.

>

**Comment by jcesarmobile** [comment]
closing, this is not a ionic-native problem
