### ISSUE TITLE
Error installing ionic native-network

### ISSUE THREAD

**Issue by crisHU10** [ionic-team/ionic-native#2904]
**Bug error:** 

```
npm install @ionic-native/network
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #5: Expected object but got boolean
npm ERR! typeerror     at inflatableChild (C:\Program Files\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:70:3)
npm ERR! typeerror     at BB.each (C:\Program Files\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:52:12)
npm ERR! typeerror     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Object.gotValue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
npm ERR! typeerror     at Object.gotAccum (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
npm ERR! typeerror     at Object.tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm ERR! typeerror     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm ERR! typeerror     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm ERR! typeerror     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm ERR! typeerror     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm ERR! typeerror     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm ERR! typeerror     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm ERR! typeerror     at runCallback (timers.js:789:20)
npm ERR! typeerror     at tryOnImmediate (timers.js:751:5)
npm ERR! typeerror     at processImmediate [as _immediateCallback] (timers.js:722:5)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2019-01-29T22_32_37_470Z-debug.log

```
**package:**

```
{
  "name": "IonicFirebaseAuth",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "compodoc": "./node_modules/.bin/compodoc -d ./docs/ -p ./tsconfig.json"
  },
  "dependencies": {
    "@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/compiler-cli": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",
    "@compodoc/compodoc": "^1.0.7",
    "@ionic-native/background-geolocation": "^4.5.3",
    "@ionic-native/core": "3.7.0",
    "@ionic-native/device": "^4.5.3",
    "@ionic-native/diagnostic": "^4.5.3",
    "@ionic-native/firebase": "^4.12.2",
    "@ionic-native/geolocation": "^4.5.3",
    "@ionic-native/google-maps": "^4.5.3",
    "@ionic-native/splash-screen": "3.7.0",
    "@ionic-native/status-bar": "3.7.0",
    "@ionic/storage": "2.0.1",
    "angularfire2": "^5.0.0-rc.3",
    "cordova-android": "7.1.0",
    "cordova-android-firebase-gradle-release": "^1.0.3",
    "cordova-android-play-services-gradle-release": "^1.4.4",
    "cordova-browser": "5.0.3",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-firebase": "^2.0.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-support-google-services": "^1.1.0",
    "cordova.plugins.diagnostic": "^3.9.2",
    "firebase": "^4.9.0",
    "geofire": "^4.1.2",
    "gulp-sass": "4.0.1",
    "heatmap.js": "^2.0.5",
    "ionic-angular": "3.2.1",
    "ionic-native": "^2.9.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "ng2-translate": "^5.0.0",
    "phonegap-plugin-multidex": "^1.0.0",
    "phonegap-plugin-push": "^2.2.3",
    "rxjs": "^5.5.12",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.10"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "typescript": "2.2.1"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-geolocation": {},
      "cordova-plugin-firebase": {},
      "cordova-android-play-services-gradle-release": {
        "PLAY_SERVICES_VERSION": "15.+"
      },
      "cordova-android-firebase-gradle-release": {
        "FIREBASE_VERSION": "15.+"
      }
    },
    "platforms": [
      "browser",
      "android"
    ]
  }
}
```

**Expected result correct installation !!**

**Best Regards.**

**Comment by mhartington** [comment]
```
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>```

Hi there! This is not an error with ionic-native, but an issue with npm. Please file your bug here

https://npm.community/c/bugs
