### ISSUE TITLE
Problems with xCode 10.2 (10E125) and Ionic 4

### ISSUE THREAD

**Issue by ivanhdzd** [ionic-team/ionic-native#2983]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
After xCode update, it show an error explaining that this xcode version not supports Switf 3, I removed my node_modules, platforms, plugins and www directory, reinstall all.

**Expected behavior:**
iOS app display my app correctly.

**Steps to reproduce:**

Ionic display an error with cordova-plugin-firebase, corrects (temporary) with [this solution](https://github.com/arnesson/cordova-plugin-firebase/issues/1033#issuecomment-477005240).
Then when build it and run (in simulator and device) run app, but not load any view, only display an empty white screen.
In Android it works correctly.
I don't know what can I do to resolve it.

xCode terminal outputs:

```bash
 2019-04-05 18:52:23.663601-0600 IonicApp[1147:377601] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///private/var/mobile/Containers/Data/Application/91F794DE-E706-40E5-BBEB-487261B553C5/Library/Cookies/Cookies.binarycookies
2019-04-05 18:52:23.697252-0600 IonicApp[1147:377706]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2019-04-05 18:52:23.782100-0600 IonicApp[1147:377601] Apache Cordova native platform version 5.0.0 is starting.
2019-04-05 18:52:23.782327-0600 IonicApp[1147:377601] Multi-tasking -> Device: YES, App: YES
2019-04-05 18:52:23.799904-0600 IonicApp[1147:377601] CDVWKWebViewEngine: trying to inject XHR polyfill
2019-04-05 18:52:23.860923-0600 IonicApp[1147:377601] CDVWKWebViewEngine will reload WKWebView if required on resume
2019-04-05 18:52:23.861172-0600 IonicApp[1147:377601] Using Ionic WKWebView
2019-04-05 18:52:23.862505-0600 IonicApp[1147:377601] [CDVTimer][console] 0.203967ms
2019-04-05 18:52:23.862848-0600 IonicApp[1147:377601] [CDVTimer][handleopenurl] 0.188947ms
2019-04-05 18:52:23.866731-0600 IonicApp[1147:377601] [CDVTimer][intentandnavigationfilter] 3.813028ms
2019-04-05 18:52:23.866925-0600 IonicApp[1147:377601] [CDVTimer][gesturehandler] 0.119925ms
2019-04-05 18:52:23.867071-0600 IonicApp[1147:377601] Starting Facebook Connect plugin
2019-04-05 18:52:23.867116-0600 IonicApp[1147:377601] [CDVTimer][facebookconnectplugin] 0.151992ms
2019-04-05 18:52:23.869544-0600 IonicApp[1147:377601] [CDVTimer][file] 2.332091ms
2019-04-05 18:52:23.869848-0600 IonicApp[1147:377601] Starting Firebase plugin
2019-04-05 18:52:23.869896-0600 IonicApp[1147:377601] [CDVTimer][firebaseplugin] 0.263929ms
2019-04-05 18:52:23.869936-0600 IonicApp[1147:377601] [CDVTimer][TotalPluginStartup] 7.786989ms
2019-04-05 18:52:23.879334-0600 IonicApp[1147:377601] GoogleService-Info.plist found, setup: [FIRApp configureWithOptions]
2019-04-05 18:52:23.904221-0600 IonicApp[1147:377601] [Crashlytics] Version 3.10.7 (130)
2019-04-05 18:52:24.027929-0600 IonicApp[1147:377704] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x2802ec100, domain=1, instance=1>
2019-04-05 18:52:24.190973-0600 IonicApp[1147:377601] FB Hybrid app events are not enabled
2019-04-05 18:52:24.461882-0600 IonicApp[1147:377601] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-04-05 18:52:24.462502-0600 IonicApp[1147:377601] [MC] Reading from public effective user settings.
2019-04-05 18:52:24.478244-0600 IonicApp[1147:377601] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x2802eea40, domain=1, instance=1>
2019-04-05 18:52:24.485818-0600 IonicApp[1147:377704] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x113d11990] get output frames failed, state 8196
2019-04-05 18:52:24.491280-0600 IonicApp[1147:377704] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x113d11990] get output frames failed, state 8196
2019-04-05 18:52:24.491770-0600 IonicApp[1147:377704] TIC Read Status [1:0x0]: 1:57
2019-04-05 18:52:24.491812-0600 IonicApp[1147:377704] TIC Read Status [1:0x0]: 1:57
2019-04-05 18:52:24.493400-0600 IonicApp[1147:377704] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x113d14550] get output frames failed, state 8196
2019-04-05 18:52:24.493608-0600 IonicApp[1147:377704] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x113d14550] get output frames failed, state 8196
2019-04-05 18:52:24.493884-0600 IonicApp[1147:377704] TIC Read Status [2:0x0]: 1:57
2019-04-05 18:52:24.493912-0600 IonicApp[1147:377704] TIC Read Status [2:0x0]: 1:57
2019-04-05 18:52:24.616680-0600 IonicApp[1147:377731] 5.7.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
2019-04-05 18:52:24.626054-0600 IonicApp[1147:377731] 5.7.0 - [Firebase/Messaging][I-FCM002023] The object <AppDelegate: 0x2802c7480> does not respond to -messaging:didReceiveRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.
2019-04-05 18:52:24.627520-0600 IonicApp[1147:377731] 5.7.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50101000 started
2019-04-05 18:52:24.627854-0600 IonicApp[1147:377731] 5.7.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2019-04-05 18:52:25.175942-0600 IonicApp[1147:377704] [Fabric] failed to download settings Error Domain=FABNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=123asd123asd123asd123asd, content_type=application/json; charset=utf-8}
2019-04-05 18:52:25.523328-0600 IonicApp[1147:377709] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C6.1:2][0x113e1cc50] get output frames failed, state 8196
2019-04-05 18:52:25.523626-0600 IonicApp[1147:377709] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C6.1:2][0x113e1cc50] get output frames failed, state 8196
2019-04-05 18:52:25.524369-0600 IonicApp[1147:377709] TIC Read Status [6:0x0]: 1:57
2019-04-05 18:52:25.524419-0600 IonicApp[1147:377709] TIC Read Status [6:0x0]: 1:57
2019-04-05 18:52:25.922002-0600 IonicApp[1147:377601] Connected to FCM.
2019-04-05 18:52:25.925432-0600 IonicApp[1147:377601] InstanceID token: XXXX
2019-04-05 18:52:26.348794-0600 IonicApp[1147:377601] Ionic Native: deviceready event fired after 1239 ms
```

**Other information:**

**Ionic info:**

Below outputs launch in terminal when I don't patch cordova plugin firebase.

```
Install complete for cordova-plugin-firebase on ios.
Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-firebase on ios platform only.
Executing script found in plugin cordova-plugin-firebase for hook "after_plugin_install": plugins/cordova-plugin-firebase/scripts/ios/after_plugin_install.js
Failed to install 'cordova-plugin-firebase': CordovaError: Using "requireCordovaModule" to load non-cordova module "xcode" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/Users/ivanhdzd/.nvm/versions/node/v10.15.1/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at Object.removeShellScriptBuildPhase (/Users/ivanhdzd/Develop/Refer/client/Refer-Users/plugins/cordova-plugin-firebase/scripts/ios/helper.js:88:25)
    at module.exports (/Users/ivanhdzd/Develop/Refer/client/Refer-Users/plugins/cordova-plugin-firebase/scripts/ios/after_plugin_install.js:8:12)
    at runScriptViaModuleLoader (/Users/ivanhdzd/.nvm/versions/node/v10.15.1/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/Users/ivanhdzd/.nvm/versions/node/v10.15.1/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /Users/ivanhdzd/.nvm/versions/node/v10.15.1/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
Using "requireCordovaModule" to load non-cordova module "xcode" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
CordovaError: Using "requireCordovaModule" to load non-cordova module "xcode" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/Users/ivanhdzd/.nvm/versions/node/v10.15.1/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at Object.removeShellScriptBuildPhase (/Users/ivanhdzd/Develop/Refer/client/Refer-Users/plugins/cordova-plugin-firebase/scripts/ios/helper.js:88:25)
    at module.exports (/Users/ivanhdzd/Develop/Refer/client/Refer-Users/plugins/cordova-plugin-firebase/scripts/ios/after_plugin_install.js:8:12)
    at runScriptViaModuleLoader (/Users/ivanhdzd/.nvm/versions/node/v10.15.1/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/Users/ivanhdzd/.nvm/versions/node/v10.15.1/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /Users/ivanhdzd/.nvm/versions/node/v10.15.1/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by praveenmenon999** [comment]
Facing similar error while taking a package build with BitBucket repo in Ionic account. Could anybody suggest some steps to mitigate this? PFA screenshot for the same.
![cordova-plugin-firebase error ionic]

(https://user-images.githubusercontent.com/42056909/56020993-ff4e3780-5d25-11e9-9a9a-b1668b705c0a.png)

**Comment by danielsogl** [comment]
Because Ionic-native is just a wrapper around the plugin itself we are unable to fix the problem.

**Comment by duongduckien** [comment]
I had a problem with Ionic 3 & Xcode 10.2.1. How about the solution? Thanks!

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 21 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/apple/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 6.1.3
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

2019-06-03 01:51:56.012825+0700 YMacau[26151:139255] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
2019-06-03 01:51:56.014276+0700 YMacau[26151:139255] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/apple/Library/Developer/CoreSimulator/Devices/A603624D-FB0D-4374-8FF9-1084D7CFBCBF/data/Containers/Data/Application/9A567BEF-DF41-4440-895D-6D0B24612AB8/Library/Cookies/com.ymacau.ymacauapp.binarycookies
2019-06-03 01:51:56.080932+0700 YMacau[26151:139255] Apache Cordova native platform version 4.5.5 is starting.
2019-06-03 01:51:56.081410+0700 YMacau[26151:139255] Multi-tasking -> Device: YES, App: YES
[ERROR] Failed binding IPv4 listening socket: Address already in use (48)
2019-06-03 01:51:56.090462+0700 YMacau[26151:139255] CDVWKWebViewEngine: trying to inject XHR polyfill
2019-06-03 01:51:56.509452+0700 YMacau[26151:139255] CDVWKWebViewEngine will reload WKWebView if required on resume
2019-06-03 01:51:56.509583+0700 YMacau[26151:139255] Using Ionic WKWebView
2019-06-03 01:51:56.510027+0700 YMacau[26151:139255] [CDVTimer][console] 0.071049ms
2019-06-03 01:51:56.510184+0700 YMacau[26151:139255] [CDVTimer][handleopenurl] 0.068069ms
2019-06-03 01:51:56.511921+0700 YMacau[26151:139255] Unlimited access to network resources
2019-06-03 01:51:56.512055+0700 YMacau[26151:139255] [CDVTimer][intentandnavigationfilter] 1.791000ms
2019-06-03 01:51:56.512178+0700 YMacau[26151:139255] [CDVTimer][gesturehandler] 0.048041ms
2019-06-03 01:51:56.514211+0700 YMacau[26151:139255] [CDVTimer][file] 1.947999ms
2019-06-03 01:51:56.517240+0700 YMacau[26151:139255] [CDVTimer][splashscreen] 2.939939ms
2019-06-03 01:51:56.521830+0700 YMacau[26151:139255] [CDVTimer][statusbar] 4.474998ms
2019-06-03 01:51:56.522025+0700 YMacau[26151:139255] [CDVTimer][googleplus] 0.054955ms
2019-06-03 01:51:56.522252+0700 YMacau[26151:139255] Starting Facebook Connect plugin
2019-06-03 01:51:56.522335+0700 YMacau[26151:139255] [CDVTimer][facebookconnectplugin] 0.154018ms
2019-06-03 01:51:56.522416+0700 YMacau[26151:139255] [CDVTimer][TotalPluginStartup] 12.485981ms
2019-06-03 01:51:56.547432+0700 YMacau[26151:139255] Falling back to loading access token from NSUserDefaults because of simulator bug
2019-06-03 01:51:56.547619+0700 YMacau[26151:139255] Falling back to storing access token in NSUserDefaults because of simulator bug
2019-06-03 01:51:56.548154+0700 YMacau[26151:139255] Falling back to loading access token from NSUserDefaults because of simulator bug
2019-06-03 01:51:56.548309+0700 YMacau[26151:139255] Falling back to storing access token in NSUserDefaults because of simulator bug
2019-06-03 01:51:56.548960+0700 YMacau[26151:139255] Falling back to loading access token from NSUserDefaults because of simulator bug
2019-06-03 01:51:56.549047+0700 YMacau[26151:139255] Falling back to storing access token in NSUserDefaults because of simulator bug
2019-06-03 01:51:56.619092+0700 YMacau[26151:139255] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/apple/Library/Developer/CoreSimulator/Devices/A603624D-FB0D-4374-8FF9-1084D7CFBCBF/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-06-03 01:51:56.619503+0700 YMacau[26151:139255] [MC] Reading from private effective user settings.
2019-06-03 01:51:57.229261+0700 YMacau[26151:139415] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x7fe253e01b20] get output frames failed, state 8196
2019-06-03 01:51:57.229383+0700 YMacau[26151:139415] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x7fe253e01b20] get output frames failed, state 8196
2019-06-03 01:51:57.229918+0700 YMacau[26151:139415] TIC Read Status [1:0x0]: 1:57
2019-06-03 01:51:57.229997+0700 YMacau[26151:139415] TIC Read Status [1:0x0]: 1:57

**Comment by mohafouad** [comment]
same problem with me :(
