### ISSUE TITLE
Ionic Native HTTP errors

### ISSUE THREAD

**Issue by russcarver** [ionic-team/ionic-native#3060]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
```
06-19 10:22:25.994  2804  3218 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getHttpUrlChecked(Ljava/lang/String;)Lokhttp3/HttpUrl; in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/com.ati.playermax-7J2_lAuR7wF-GmEJjCeAYw==/base.apk!classes4.dex)
06-19 10:22:25.994  2804  3218 E AndroidRuntime: 	at com.silkimen.cordovahttp.CordovaHttpBase.sendBody(CordovaHttpBase.java:153)
06-19 10:22:25.994  2804  3218 E AndroidRuntime: 	at com.silkimen.cordovahttp.CordovaHttpBase.run(CordovaHttpBase.java:77)
06-19 10:22:25.997  1369  2009 W ActivityManager: crash
```

**Expected behavior:**
The HTTP calls should work.

**Steps to reproduce:**
Make a post call.

**Related code:**
Here are the relative bits:
```
import { HTTP } from '@ionic-native/http/ngx';

private advancedHttp: HTTP // in constructor

return await this.advancedHttp.post(url, body, headers); // in a method
```
`url` is https.
`body` is JSON object (strings)
`headers` is JSON object (strings) consisting of CorpProp, DeviceToken and Client-ID.

**Other information:**
This happens whether or not I use `setSSLCertMode('nocheck');` or `setSSLCertMode('pinned');`
I'm using version 2.1.1 of cordova-plugin-advanced-http

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/rc101077/Library/Android/sdk)
   ios-sim           : 8.0.1
   NodeJS            : v10.16.0 (/Users/rc101077/.nvm/versions/node/v10.16.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by russcarver** [comment]
It turns out this issue was a conflict with another plugin (geofence) using `com.squareup.okhttp3:okhttp-urlconnection:3.11.0`. I added the following variable to my `config.xml` to solve the issue.
```
<plugin name="cordova-plugin-advanced-http" spec="2.1.1">
        <variable name="OKHTTP_VERSION" value="3.11.0" />
</plugin>
```
