### ISSUE TITLE
Background mode disableWebViewOptimizations doesn't work

### ISSUE THREAD

**Issue by chujzaurus** [ionic-team/ionic-native#3092]
[ x ] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
```
  this.backgroundMode.on('enable').subscribe(() => {
            this.backgroundMode.disableWebViewOptimizations();
        });
```
Crashes on Android. 

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.comp.testapp, PID: 7826
    java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View org.apache.cordova.CordovaWebViewEngine.getView()' on a null object reference
        at de.appplant.cordova.plugin.background.BackgroundModeExt$1.lambda$run$0$BackgroundModeExt$1(BackgroundModeExt.java:169)
        at de.appplant.cordova.plugin.background.-$$Lambda$BackgroundModeExt$1$G8BcCUGm1NdL43D3hx0oXWRmZqc.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
E/com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mainjava.lang.NullPointerException: Attempt to invoke interface method 'android.view.View org.apache.cordova.CordovaWebViewEngine.getView()' on a null object reference
        at de.appplant.cordova.plugin.background.BackgroundModeExt$1.lambda$run$0$BackgroundModeExt$1(BackgroundModeExt.java:169)
        at de.appplant.cordova.plugin.background.-$$Lambda$BackgroundModeExt$1$G8BcCUGm1NdL43D3hx0oXWRmZqc.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

For some reason webView is null. I am not sure how to approach this. 

**Expected behavior:**
Should work. 

**Steps to reproduce:**

**Related code:**

```
  initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
      this.connectivityService.initializeNetworkEvents();
      if (this.platform.is('android')) {
        this.backgroundMode.setDefaults({silent:true});
        this.backgroundMode.on('enable').subscribe(() => {
            this.backgroundMode.disableWebViewOptimizations();
        });
        this.backgroundMode.enable();
      }
    });
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Ionic:

   Ionic CLI                     : 5.1.0 (C:\Users\user\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.0, (and 11 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.4

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.0
   OS     : Windows 10

**Comment by renatop7** [comment]
Hey, did you find a solution for this?

**Comment by alterx** [comment]
I found this one too (using a fork of the same plugin). See https://bitbucket.org/TheBosZ/cordova-plugin-run-in-background/issues/16/error-when-calling

It looks like the issue lies here: https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java#L262

Should this be reported here or in the Capacitor repo?

**Comment by TheBosZ** [comment]
I [updated my fork](https://bitbucket.org/TheBosZ/cordova-plugin-run-in-background/commits/8d523e638e62a09a630d91878f2dbeb44a4c621e) (that @alterx linked to) to use `.getView()` rather than `.getEngine().getView()` but he's reporting that the error persists.

**Comment by alterx** [comment]
Looking at the code I was puzzled about why your fix didn't work so I cleaned up everything and did a fresh reinstall of the latest `master` again. This time the app didn't crash.

**Comment by alpadilla** [comment]
The solution is here, [https://github.com/katzer/cordova-plugin-background-mode/pull/542/commits/0bc885ca34c2d602f7a373d316dc1ffc67cf4d83](url), There is a pending PR since 14 Dec 2020.
It's working for me.
