### ISSUE TITLE
@ionic-native/media: No audio output, no error message (targetting API 28)

### ISSUE THREAD

**Issue by NorthFred** [ionic-team/ionic-native#3129]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
On Android v.9, there is no audio output and no error/exception is thrown.

**Expected behavior:**
Audio output expected, as is the case on older (< v.9) Android versions.

**Steps to reproduce:**

**Related code:**

Code was working fine when project was targetted at API 27 (running on Android 9). After performing mandatory update for Google Play publishing to API 28, the audio was no longer playing on Android 9 devices.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI          : 5.2.3 (C:\Users\xxx\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.8
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 16 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (D:\AndroidDevelopmentSDK)
   NodeJS            : v8.9.4 (D:\NodeJS\node.exe)
   npm               : 6.8.0
   OS                : Windows 10
```

**Package.json:**

```
{
  "name": "My App",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "^8.2.0",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/app-availability": "^5.11.0",
    "@ionic-native/app-version": "^5.11.0",
    "@ionic-native/core": "^5.11.0",
    "@ionic-native/device": "^5.11.0",
    "@ionic-native/http": "^5.11.0",
    "@ionic-native/in-app-browser": "^5.11.0",
    "@ionic-native/market": "^5.11.0",
    "@ionic-native/media": "^5.11.0",
    "@ionic-native/mobile-accessibility": "^5.11.0",
    "@ionic-native/music-controls": "^5.11.0",
    "@ionic-native/network": "^5.11.0",
    "@ionic-native/photo-viewer": "^5.11.0",
    "@ionic-native/splash-screen": "^5.11.0",
    "@ionic-native/status-bar": "^5.11.0",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "8.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "@ultimate/ngxerrors": "^1.4.0",
    "angularfire2": "^5.1.1",
    "com-sarriaroman-photoviewer": "1.2.4",
    "cordova": "^9.0.0",
    "cordova-android": "8.0.0",
    "cordova-browser": "5.0.4",
    "cordova-plugin-advanced-http": "^2.1.1",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-appavailability": "^0.4.2",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-foreground-service": "git+https://github.com/DavidBriglio/cordova-plugin-foreground-service.git",
    "cordova-plugin-inappbrowser": "3.1.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^3.1.2",
    "cordova-plugin-market": "1.2.0",
    "cordova-plugin-media": "^5.0.3",
    "cordova-plugin-music-controls": "2.2.0",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-powermanagement-orig": "git+https://github.com/boltex/cordova-plugin-powermanagement.git",
    "cordova-plugin-splashscreen": "5.0.3",
    "cordova-plugin-statusbar": "2.4.3",
    "cordova-plugin-whitelist": "1.3.4",
    "firebase": "^5.7.3",
    "ionic-angular": "^3.9.8",
    "ionicons": "3.0.0",
    "phonegap-plugin-mobile-accessibility": "^1.0.5",
    "rxjs": "^5.6.0-forward-compat.5",
    "rxjs-compat": "^6.4.0",
    "sw-toolbox": "3.6.0",
    "uninstall": "0.0.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.2.3",
    "typescript": "^2.6.2"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-network-information": {},
      "phonegap-plugin-mobile-accessibility": {},
      "cordova-plugin-foreground-service": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-advanced-http": {
        "OKHTTP_VERSION": "3.10.0"
      },
      "cordova-plugin-appavailability": {},
      "cordova-plugin-file": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-market": {},
      "com-sarriaroman-photoviewer": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-music-controls": {},
      "cordova-plugin-media": {}
    },
    "platforms": [
      "browser",
      "android"
    ]
  }
}
```

**Config.xml:**

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="xxxxxxxxxxxxxxxx" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>AppName</name>
    <access origin="*" />
    <allow-intent href="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-intent href="fb://*" />
    <allow-intent href="fb://*/*" />
    <allow-navigation href="*" />
    <allow-navigation href="data:*" />
    <preference name="AndroidPersistentFileLocation" value="Compatibility" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="KeepRunning" value="true" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="android-targetSdkVersion" value="28" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="ShowSplashScreen" value="true" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreenSpinnerColor" value="#C39229" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="FadeSplashScreen" value="true" />
    <preference name="FadeSplashScreenDuration" value="1000" />
    <preference name="orientation" value="portrait" />
    <platform name="android">
        <config-file parent="/*" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
            <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
            <uses-permission android:name="android.permission.WAKE_LOCK" />
            <uses-permission android:name="android.permission.INTERNET" />
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
            <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
        </config-file>
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <allow-navigation href="http://192.168.8.100:8100" sessionid="bd5eb56e" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.3" />
    <plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.3" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.1.3" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="phonegap-plugin-mobile-accessibility" spec="^1.0.5" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.4" />
    <plugin name="cordova-plugin-foreground-service" spec="git+https://github.com/DavidBriglio/cordova-plugin-foreground-service.git" />
    <plugin name="cordova-plugin-app-version" spec="0.1.9" />
    <plugin name="cordova-plugin-advanced-http" spec="2.1.1">
        <variable name="OKHTTP_VERSION" value="3.10.0" />
    </plugin>
    <plugin name="cordova-plugin-inappbrowser" spec="3.0.0" />
    <plugin name="cordova-plugin-appavailability" spec="0.4.2" />
    <plugin name="cordova-plugin-media" spec="5.0.3" />
    <plugin name="cordova-plugin-ionic-webview" spec="^3.1.2">
        <variable name="ANDROID_SUPPORT_ANNOTATIONS_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-market" spec="1.2.0" />
    <plugin name="com-sarriaroman-photoviewer" spec="1.2.4" />
    <plugin name="cordova-plugin-music-controls" spec="https://github.com/amitkhare/cordova-music-controls-plugin" />
    <engine name="browser" spec="5.0.4" />
    <engine name="android" spec="8.0.0" />
</widget>
```

**Comment by NorthFred** [comment]
Taking a log with adb gives this result:

```
08-06 18:49:09.734   594   787 D AudioFlinger: event 163 
08-06 18:49:09.734 26130 26152 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.URLConnection java.net.URL.openConnection()' on a null object reference
08-06 18:49:09.735 26130 26152 W System.err: 	at android.media.MediaHTTPConnection.seekTo(MediaHTTPConnection.java:210)
08-06 18:49:09.735 26130 26152 W System.err: 	at android.media.MediaHTTPConnection.getSize(MediaHTTPConnection.java:414)
08-06 18:49:09.735 26130 26152 W System.err: 	at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:81)
08-06 18:49:09.735 26130 26152 W System.err: 	at android.os.Binder.execTransact(Binder.java:739)
08-06 18:49:09.738   682  1568 E AMRExtractor: read header failed!
```

**Comment by NorthFred** [comment]
Found the solution:

https://developer.android.com/training/articles/security-config

The error occurred because my app was streaming music / media over HTTP. When targeting API level 28 (Android P), the default security is HTTPS. So by adding the ```<application android:usesCleartextTraffic="true" />``` tag to the AndroidManifest / config.xml, I was able to default to the HTTP security.
