### ISSUE TITLE
Camera plugin does not work for Windows platform

### ISSUE THREAD

**Issue by srinidhirao** [ionic-team/ionic-native#3275]
**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Create a new Ionic 4 app & add the [camera plugin](https://ionicframework.com/docs/native/camera). Calling any function on the camera plugin fails with the following error. However, the ionic project comes in-built with the status bar plugin. Calling a function on status bar plugin works without issues. The same Ionic app does not show issues accessing Camera Plugin in Android or iOS.

This is the error when trying to access a function on Camera Plugin

````
Exception was thrown at line 81605, column 56 in ms-appx-web://io.ionic.starter/www/build/vendor.js
0x800a138a - JavaScript runtime error: Function expected
Exception was thrown at line 15744, column 9 in ms-appx-web://io.ionic.starter/www/build/vendor.js
0x800a138a - JavaScript runtime error: Function expected
Exception was thrown at line 3, column 19746 in ms-appx-web://io.ionic.starter/www/build/polyfills.js
0x800a139e - JavaScript runtime error: Uncaught (in promise): TypeError: Function expected
TypeError: Function expected
   at Camera.prototype.getPicture (ms-appx-web://io.ionic.starter/www/build/vendor.js:81605:56)
   at ContactPage (ms-appx-web://io.ionic.starter/www/build/main.js:146:9)
   at createClass (ms-appx-web://io.ionic.starter/www/build/vendor.js:13119:13)
   at createDirectiveInstance (ms-appx-web://io.ionic.starter/www/build/vendor.js:12962:5)
   at createViewNodes (ms-appx-web://io.ionic.starter/www/build/vendor.js:14420:21)
   at createRootView (ms-appx-web://io.ionic.starter/www/build/vendor.js:14309:5)
   at callWithDebugContext (ms-appx-web://io.ionic.starter/www/build/vendor.js:15734:9)
   at debugCreateRootView (ms-appx-web://io.ionic.starter/www/build/vendor.js:15017:5)
   at ComponentFactory_.prototype.create (ms-appx-web://io.ionic.starter/www/build/vendor.js:11914:9)
   at ComponentFactoryBoundToModule.prototype.create (ms-appx-web://io.ionic.starter/www/build/vendor.js:4666:9)
````

**Expected behavior:**
The camera plugin should work as documented.

**Steps to reproduce:**
1. Create a New Ionic 4 project.
2. Add windows platform
3. Add camera plugin
4. Try to call any of the methods of the camera plugin.
5. The function errors with the above error.

**Other information:**
I encountered the same issue with other Ionic plugins like SplashScreen. Does Ionic 4 support Windows as a platform?

Upon inspecting the instance variable of the Camera plugin, one can see that all properties are available for use.

![Image_with_all_Properties](https://user-images.githubusercontent.com/9901457/71721535-70e98b00-2e4b-11ea-823b-e36119402ba1.PNG)

However, accessing a function like getPicture() results in a exception:

![Image_when_trying_to_access_getPicture_function](https://user-images.githubusercontent.com/9901457/71721618-c0c85200-2e4b-11ea-8e1b-b7cbed802829.PNG)

Comparing this with the status bar plugin, the debug structure looks similar and accessing a function works.

![using_statusbar_plugin](https://user-images.githubusercontent.com/9901457/71721584-a1312980-2e4b-11ea-895b-e1236735f575.PNG)

![calling_a_function_on_status_bar](https://user-images.githubusercontent.com/9901457/71721588-a3938380-2e4b-11ea-99cc-99c813be0ddb.PNG)

I then compared the ionic wrapper for both the plugins and found that the Ionic wrapper structure is quite different. The camera plugin has a ngx folder whereas the status bar plugin doesn't. I guess the status bar plugin is using the ionic 3 format and the camera the latest ionic 4 format?

When I look at the import statements, status bar plugin is actually not referred from a ngx folder, which leads me to thinking that status bar is using old version of the plugin.

````
import { Camera, CameraOptions } from '@ionic-native/camera/ngx';
import { StatusBar } from '@ionic-native/status-bar';
````
Camera Plugin's Ionic Wrapper
[camera.zip](https://github.com/ionic-team/ionic-native/files/4018994/camera.zip)

Status bar Plugin's Ionic Wrapper
[status-bar.zip](https://github.com/ionic-team/ionic-native/files/4018995/status-bar.zip)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
C:\Users\VPNUser\Documents\MyIonicProject>ionic info

Ionic:

   ionic (Ionic CLI)  : 4.5.0 (C:\Users\VPNUser\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : windows 6.0.1
   Cordova Plugins       : not available

System:

   NodeJS : v12.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by srinidhirao** [comment]
@danielsogl Can you please take a look at this? 

Looks like the ionic native wrapper is impacting the functionality of a Cordova plugin when used in Windows 10 environment.  I created a new project which integrates with the camera plugin without using ionic native and it works without any issues. 

I have captured a short video of the same which you can find here:
https://repo.unvired.io/unvired/ionic-native-camera-plugin-example.mp4

Please find the relevant code here:
```
declare var navigator: any;
// This works.
onCameraButtonWithoutIonicNativeClick() {
    console.log('Camera Button Clicked');
    navigator.camera.getPicture(function onSuccess(success) {
      console.log("Successfully clicked the picture:" + success);
    }, function onError(error) {
      console.log("Error Capturing the picture: " + error);
    }, {})
  }

// This doesn't.
  onCameraButtonWithIonicNativeClick() {
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    }

    this.camera.getPicture(options).then((imageData) => {
      // imageData is either a base64 encoded string or a file URI
      // If it's base64 (DATA_URL):
      let base64Image = 'data:image/jpeg;base64,' + imageData;
      console.log("Base 64: " + base64Image);
    }, (err) => {
      // Handle error
      console.log("Error: " + err)
    });
  }

```
Can you please take a look at this once again? 

This is the link to my repository
https://github.com/srinidhirao/windows-10-sample
